/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'dashboards-analytics': RouteRecordInfo<'dashboards-analytics', '/dashboards/analytics', Record<never, never>, Record<never, never>>,
    'event': RouteRecordInfo<'event', '/event', Record<never, never>, Record<never, never>>,
    'event-products': RouteRecordInfo<'event-products', '/event/products', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'iconcash-balance': RouteRecordInfo<'iconcash-balance', '/iconcash/balance', Record<never, never>, Record<never, never>>,
    'iconcash-bank': RouteRecordInfo<'iconcash-bank', '/iconcash/bank', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'merchant-tab': RouteRecordInfo<'merchant-tab', '/merchant/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'pages-about': RouteRecordInfo<'pages-about', '/pages/about', Record<never, never>, Record<never, never>>,
    'pages-faq': RouteRecordInfo<'pages-faq', '/pages/faq', Record<never, never>, Record<never, never>>,
    'pages-privacy': RouteRecordInfo<'pages-privacy', '/pages/privacy', Record<never, never>, Record<never, never>>,
    'pages-terms': RouteRecordInfo<'pages-terms', '/pages/terms', Record<never, never>, Record<never, never>>,
    'pesanan-tab': RouteRecordInfo<'pesanan-tab', '/pesanan/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pesanan-invoice-id': RouteRecordInfo<'pesanan-invoice-id', '/pesanan/invoice/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pesanan-view-id': RouteRecordInfo<'pesanan-view-id', '/pesanan/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'produk-tab': RouteRecordInfo<'produk-tab', '/produk/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'produk-edit-id': RouteRecordInfo<'produk-edit-id', '/produk/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'produk-preview-id': RouteRecordInfo<'produk-preview-id', '/produk/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'produk-tambah-tab': RouteRecordInfo<'produk-tambah-tab', '/produk/tambah/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'produk-view-id': RouteRecordInfo<'produk-view-id', '/produk/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'promo': RouteRecordInfo<'promo', '/promo', Record<never, never>, Record<never, never>>,
    'promo-products': RouteRecordInfo<'promo-products', '/promo/products', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    'verification': RouteRecordInfo<'verification', '/verification', Record<never, never>, Record<never, never>>,
  }
}
