// {
//     "success": true,
//     "message": "Data berhasil didapatkan",
//     "status_code": 200,
//     "data": {
//         "total": 53,
//         "data": [
//             {
//                 "id": 243735,
//                 "merchant_id": 5456,
//                 "name": "Kaos hitam keren",
//                 "price": "990000",
//                 "strike_price": "100000",
//                 "minimum_purchase": 1,
//                 "category_id": 502,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "1000",
//                 "description": "kaos hitam yang sangat keren, cocok digunakan orang keren, dengan baju ini anda akan terlihat pede. ",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "JNE",
//                 "is_featured_product": false,
//                 "created_by": "NAGA",
//                 "updated_by": "TOKO NAGA 2",
//                 "created_at": "2024-04-18T10:49:35Z",
//                 "updated_at": "2024-12-20T16:05:19Z",
//                 "deleted_at": null,
//                 "status": 9,
//                 "items_sold": 9,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "2",
//                 "height": "8",
//                 "width": "5",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 822631,
//                         "merchant_id": 5456,
//                         "product_id": 243735,
//                         "amount": 100,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"adding\", \"title\": \"Update stok produk\", \"amount\": \"100\"}",
//                         "status": 1,
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:29:23Z",
//                         "updated_at": "2024-11-21T10:29:23Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167685,
//                         "merchant_id": 5456,
//                         "product_id": 243735,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~1727071819dca896dd-73f3-449a-8367-0987985ae903.jpg",
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:29:23Z",
//                         "updated_at": "2024-11-21T10:29:23Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 502,
//                     "type": "product_category",
//                     "key": "prodcat_mobil_listrik_1",
//                     "value_type": "string",
//                     "value": "Mobil Listrik",
//                     "parent_id": 373,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": null,
//                     "created_at": "2023-03-09T16:51:37Z",
//                     "updated_at": "2023-03-09T16:51:37Z",
//                     "deleted_at": null,
//                     "max_variant": null,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             },
//             {
//                 "id": 243745,
//                 "merchant_id": 5456,
//                 "name": "Hitam Baju",
//                 "price": "500000",
//                 "strike_price": "500000",
//                 "minimum_purchase": 1,
//                 "category_id": 107,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "1000",
//                 "description": "Baju kaos hitam sekali banget hitam, keren dan mantap sekali bahannya bagus dan nyaman dipakai oleh manusia",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "JNE",
//                 "is_featured_product": false,
//                 "created_by": "NAGA",
//                 "updated_by": "TOKO NAGA 2",
//                 "created_at": "2024-05-29T18:58:16Z",
//                 "updated_at": "2024-10-22T13:44:51Z",
//                 "deleted_at": null,
//                 "status": 1,
//                 "items_sold": 21,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "10",
//                 "height": "10",
//                 "width": "10",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 829146,
//                         "merchant_id": 5456,
//                         "product_id": 243745,
//                         "amount": 924,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"changing\", \"title\": \"Ubah stok produk\", \"amount\": \"924\"}",
//                         "status": 1,
//                         "created_by": null,
//                         "updated_by": "Update By Scheduler",
//                         "created_at": "2024-10-22T13:44:51Z",
//                         "updated_at": "2024-10-22T13:44:51Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167659,
//                         "merchant_id": 5456,
//                         "product_id": 243745,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~17169838950a61a8f8-9614-4935-a01c-39fa0820203e.jpg",
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-10-22T13:44:51Z",
//                         "updated_at": "2024-10-22T13:44:51Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 107,
//                     "type": "product_category",
//                     "key": "prodcat_baju_pria",
//                     "value_type": "string",
//                     "value": "Baju Pria",
//                     "parent_id": 104,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": "Service Provider",
//                     "created_at": "2021-10-30T17:02:25Z",
//                     "updated_at": "2021-10-30T17:09:03Z",
//                     "deleted_at": null,
//                     "max_variant": null,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             },
//             {
//                 "id": 243773,
//                 "merchant_id": 5456,
//                 "name": "Bangku Kantor 2",
//                 "price": "877500",
//                 "strike_price": "350000",
//                 "minimum_purchase": 1,
//                 "category_id": 304,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "100",
//                 "description": "Bangku Kantor yang kokoh dan sangat elegan, sangat cocok ketika anda duduk di singga sana tersebut, anda akan terlihat tampan, cantik, dan keren",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "JNE",
//                 "is_featured_product": true,
//                 "created_by": "NAGA",
//                 "updated_by": "TOKO NAGA 2",
//                 "created_at": "2024-07-23T15:31:51Z",
//                 "updated_at": "2024-12-31T10:44:17Z",
//                 "deleted_at": null,
//                 "status": 1,
//                 "items_sold": 42,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "1",
//                 "height": "1",
//                 "width": "1",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 829166,
//                         "merchant_id": 5456,
//                         "product_id": 243773,
//                         "amount": 153,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"changing\", \"title\": \"Ubah stok produk\", \"amount\": \"153\"}",
//                         "status": 1,
//                         "created_by": null,
//                         "updated_by": "Update By Scheduler",
//                         "created_at": "2024-12-31T10:44:17Z",
//                         "updated_at": "2024-12-31T10:44:17Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167744,
//                         "merchant_id": 5456,
//                         "product_id": 243773,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~172172350916a249ac-7277-4ef9-89e6-83ea49dc7f8a.jpg",
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-12-31T10:44:17Z",
//                         "updated_at": "2024-12-31T10:44:17Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 304,
//                     "type": "product_category",
//                     "key": "prodcat_lainya",
//                     "value_type": "string",
//                     "value": "Lainya",
//                     "parent_id": 303,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": null,
//                     "created_at": "2021-11-04T08:43:50Z",
//                     "updated_at": "2021-11-04T08:43:50Z",
//                     "deleted_at": null,
//                     "max_variant": null,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             },
//             {
//                 "id": 243774,
//                 "merchant_id": 5456,
//                 "name": "Kulkas 2 Pintu",
//                 "price": "3000000",
//                 "strike_price": "7000000",
//                 "minimum_purchase": 1,
//                 "category_id": 358,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "50000",
//                 "description": "Kulkas 2 pintu sangat berkualitas dan sangat serbaguna dan mantap, serbaguna untuk keluarga terima kasih",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "JNE",
//                 "is_featured_product": true,
//                 "created_by": "NAGA",
//                 "updated_by": "NAGA",
//                 "created_at": "2024-07-23T17:02:29Z",
//                 "updated_at": "2024-10-14T10:23:38Z",
//                 "deleted_at": null,
//                 "status": 1,
//                 "items_sold": 12,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "20",
//                 "height": "150",
//                 "width": "20",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 829167,
//                         "merchant_id": 5456,
//                         "product_id": 243774,
//                         "amount": 29,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"changing\", \"title\": \"Ubah stok produk\", \"amount\": \"29\"}",
//                         "status": 1,
//                         "created_by": "NAGA",
//                         "updated_by": "Update By Scheduler",
//                         "created_at": "2024-07-23T17:02:29Z",
//                         "updated_at": "2024-07-23T17:02:29Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167632,
//                         "merchant_id": 5456,
//                         "product_id": 243774,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~172172894826c89a3b-7ca5-49b7-a30e-0375c1f2d037.jpg",
//                         "created_by": "NAGA",
//                         "updated_by": "NAGA",
//                         "created_at": "2024-10-14T10:23:38Z",
//                         "updated_at": "2024-10-14T10:23:38Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 358,
//                     "type": "product_category",
//                     "key": "prodcat_kulkas",
//                     "value_type": "string",
//                     "value": "Kulkas",
//                     "parent_id": 346,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": null,
//                     "created_at": "2022-05-24T10:33:57Z",
//                     "updated_at": "2022-05-24T10:33:57Z",
//                     "deleted_at": null,
//                     "max_variant": 1,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             },
//             {
//                 "id": 243775,
//                 "merchant_id": 5456,
//                 "name": "Smart TV 32inci",
//                 "price": "1000000",
//                 "strike_price": "2000000",
//                 "minimum_purchase": 1,
//                 "category_id": 333,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "10000",
//                 "description": "Tv ini sangat keren dan hebat, apalagi anda yang beli hp ini, pasti ganteng ganteng dan keren sekali anda",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "",
//                 "is_featured_product": false,
//                 "created_by": "NAGA",
//                 "updated_by": "TOKO NAGA 2",
//                 "created_at": "2024-07-23T17:10:06Z",
//                 "updated_at": "2024-12-14T17:30:04Z",
//                 "deleted_at": null,
//                 "status": 1,
//                 "items_sold": 42,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "10",
//                 "height": "10",
//                 "width": "10",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 829168,
//                         "merchant_id": 5456,
//                         "product_id": 243775,
//                         "amount": 105,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"changing\", \"title\": \"Ubah stok produk\", \"amount\": \"105\"}",
//                         "status": 1,
//                         "created_by": null,
//                         "updated_by": "Achmad Nagaria",
//                         "created_at": "2024-12-13T10:57:20Z",
//                         "updated_at": "2024-12-13T10:57:20Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167736,
//                         "merchant_id": 5456,
//                         "product_id": 243775,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~1721729404cac7da64-901c-4dba-b4c2-0dc8abb79daa.jpg",
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-12-13T10:57:20Z",
//                         "updated_at": "2024-12-13T10:57:20Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 333,
//                     "type": "product_category",
//                     "key": "prodcat_peralatan_memasak",
//                     "value_type": "string",
//                     "value": "Peralatan Memasak",
//                     "parent_id": 330,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": null,
//                     "created_at": "2022-01-26T09:48:55Z",
//                     "updated_at": "2022-01-26T09:48:55Z",
//                     "deleted_at": null,
//                     "max_variant": 0,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             },
//             {
//                 "id": 243838,
//                 "merchant_id": 5456,
//                 "name": "Sepeda Listrik 1",
//                 "price": "5000000",
//                 "strike_price": "10000000",
//                 "minimum_purchase": 1,
//                 "category_id": 501,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "10000",
//                 "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "JNE",
//                 "is_featured_product": false,
//                 "created_by": "TOKO NAGA 2",
//                 "updated_by": "TOKO NAGA 2",
//                 "created_at": "2024-11-21T10:35:36Z",
//                 "updated_at": "2024-11-21T10:35:36Z",
//                 "deleted_at": null,
//                 "status": 1,
//                 "items_sold": 0,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "100",
//                 "height": "100",
//                 "width": "100",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 829198,
//                         "merchant_id": 5456,
//                         "product_id": 243838,
//                         "amount": 10,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"adding\", \"title\": \"Tambah stok produk baru\", \"amount\": \"10\"}",
//                         "status": 1,
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:35:36Z",
//                         "updated_at": "2024-11-21T10:35:36Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167686,
//                         "merchant_id": 5456,
//                         "product_id": 243838,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~17321601350ddd6002-fcc2-408a-9494-bd6d721e9c41.jpg",
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:35:36Z",
//                         "updated_at": "2024-11-21T10:35:36Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 501,
//                     "type": "product_category",
//                     "key": "prodcat_sepeda_listrik",
//                     "value_type": "string",
//                     "value": "Sepeda Listrik",
//                     "parent_id": 373,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": null,
//                     "created_at": "2022-01-27T13:59:56Z",
//                     "updated_at": "2022-01-27T13:59:56Z",
//                     "deleted_at": null,
//                     "max_variant": 0,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             },
//             {
//                 "id": 243839,
//                 "merchant_id": 5456,
//                 "name": "Sepeda Listrik 2",
//                 "price": "2000000",
//                 "strike_price": "3000000",
//                 "minimum_purchase": 1,
//                 "category_id": 501,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "10000",
//                 "description": "{\"name\":\"Sepeda Listrik 1\",\"uom\":\"(Gr)\",\"condition\":\"Baru\",\"weight\":\"10000\",\"length\":\"100\",\"width\":\"100\",\"height\":\"100\",\"strike_price\":10000000.0,\"description\":\"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\",\"shipping_service\":\"JNE\",\"is_featured_product\":false,\"minimum_purchase\":1,\"product_id\":null,\"merchant_id\":5456,\"category_id\":501,\"etalase_id\":2691,\"amount\":10,\"price\":5000000.0,\"url\":[\"https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~17321601350ddd6002-fcc2-408a-9494-bd6d721e9c41.jpg\"],\"is_shipping_insurance\":false,\"variant\":[],\"variant_value_product\":[]}",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "JNE",
//                 "is_featured_product": false,
//                 "created_by": "TOKO NAGA 2",
//                 "updated_by": "TOKO NAGA 2",
//                 "created_at": "2024-11-21T10:36:32Z",
//                 "updated_at": "2024-12-18T10:03:03Z",
//                 "deleted_at": null,
//                 "status": 9,
//                 "items_sold": 0,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "100",
//                 "height": "100",
//                 "width": "100",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 829199,
//                         "merchant_id": 5456,
//                         "product_id": 243839,
//                         "amount": 100,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"adding\", \"title\": \"Tambah stok produk baru\", \"amount\": \"100\"}",
//                         "status": 1,
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:36:32Z",
//                         "updated_at": "2024-11-21T10:36:32Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167687,
//                         "merchant_id": 5456,
//                         "product_id": 243839,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~1732160191d5a37b22-2eab-4069-babd-f154423b70c4.jpg",
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:36:32Z",
//                         "updated_at": "2024-11-21T10:36:32Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 501,
//                     "type": "product_category",
//                     "key": "prodcat_sepeda_listrik",
//                     "value_type": "string",
//                     "value": "Sepeda Listrik",
//                     "parent_id": 373,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": null,
//                     "created_at": "2022-01-27T13:59:56Z",
//                     "updated_at": "2022-01-27T13:59:56Z",
//                     "deleted_at": null,
//                     "max_variant": 0,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             },
//             {
//                 "id": 243840,
//                 "merchant_id": 5456,
//                 "name": "Motor Listrik",
//                 "price": "15000000",
//                 "strike_price": "25000000",
//                 "minimum_purchase": 1,
//                 "category_id": 458,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "10",
//                 "description": "Motor Listrik Bagus kuat dan mantap keren mantap jiwa, murah meriah mantap banget kawan asik nihh... ",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "JNE",
//                 "is_featured_product": false,
//                 "created_by": "TOKO NAGA 2",
//                 "updated_by": "TOKO NAGA 2",
//                 "created_at": "2024-11-21T10:37:03Z",
//                 "updated_at": "2024-11-21T10:37:03Z",
//                 "deleted_at": null,
//                 "status": 1,
//                 "items_sold": 0,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "150",
//                 "height": "100",
//                 "width": "100",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 829200,
//                         "merchant_id": 5456,
//                         "product_id": 243840,
//                         "amount": 100,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"adding\", \"title\": \"Tambah stok produk baru\", \"amount\": \"100\"}",
//                         "status": 1,
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:37:03Z",
//                         "updated_at": "2024-11-21T10:37:03Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167688,
//                         "merchant_id": 5456,
//                         "product_id": 243840,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~1732160221bc1a5bbd-a4b7-4f33-85cf-fa3c5ac1c521.jpg",
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:37:03Z",
//                         "updated_at": "2024-11-21T10:37:03Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 458,
//                     "type": "product_category",
//                     "key": "prodcat_motor_listrik_2",
//                     "value_type": "string",
//                     "value": "Motor Listrik",
//                     "parent_id": 373,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": null,
//                     "created_at": "2022-01-27T13:59:56Z",
//                     "updated_at": "2022-01-27T13:59:56Z",
//                     "deleted_at": null,
//                     "max_variant": 0,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             },
//             {
//                 "id": 243841,
//                 "merchant_id": 5456,
//                 "name": "Sepeda Listrik 3",
//                 "price": "2000000",
//                 "strike_price": "3000000",
//                 "minimum_purchase": 1,
//                 "category_id": 501,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "10000",
//                 "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "JNE",
//                 "is_featured_product": false,
//                 "created_by": "TOKO NAGA 2",
//                 "updated_by": "TOKO NAGA 2",
//                 "created_at": "2024-11-21T10:45:19Z",
//                 "updated_at": "2024-11-21T10:45:19Z",
//                 "deleted_at": null,
//                 "status": 1,
//                 "items_sold": 0,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "100",
//                 "height": "100",
//                 "width": "100",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 829201,
//                         "merchant_id": 5456,
//                         "product_id": 243841,
//                         "amount": 100,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"adding\", \"title\": \"Tambah stok produk baru\", \"amount\": \"100\"}",
//                         "status": 1,
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:45:19Z",
//                         "updated_at": "2024-11-21T10:45:19Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167689,
//                         "merchant_id": 5456,
//                         "product_id": 243841,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~1732160191d5a37b22-2eab-4069-babd-f154423b70c4.jpg",
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:45:19Z",
//                         "updated_at": "2024-11-21T10:45:19Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 501,
//                     "type": "product_category",
//                     "key": "prodcat_sepeda_listrik",
//                     "value_type": "string",
//                     "value": "Sepeda Listrik",
//                     "parent_id": 373,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": null,
//                     "created_at": "2022-01-27T13:59:56Z",
//                     "updated_at": "2022-01-27T13:59:56Z",
//                     "deleted_at": null,
//                     "max_variant": 0,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             },
//             {
//                 "id": 243842,
//                 "merchant_id": 5456,
//                 "name": "Sepeda Listrik 4",
//                 "price": "2000000",
//                 "strike_price": "3000000",
//                 "minimum_purchase": 1,
//                 "category_id": 501,
//                 "etalase_id": 2691,
//                 "condition": "Baru",
//                 "weight": "10000",
//                 "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
//                 "is_shipping_insurance": false,
//                 "shipping_service": "JNE",
//                 "is_featured_product": false,
//                 "created_by": "TOKO NAGA 2",
//                 "updated_by": "TOKO NAGA 2",
//                 "created_at": "2024-11-21T10:45:28Z",
//                 "updated_at": "2024-11-21T10:45:28Z",
//                 "deleted_at": null,
//                 "status": 1,
//                 "items_sold": 0,
//                 "avg_rating": "0",
//                 "review_count": 0,
//                 "is_flash_sale_discount": false,
//                 "length": "100",
//                 "height": "100",
//                 "width": "100",
//                 "stock": 0,
//                 "sold": 0,
//                 "order_details_count": 0,
//                 "event_badge_active": false,
//                 "event_badge_image_url": "",
//                 "product_stock": [
//                     {
//                         "id": 829202,
//                         "merchant_id": 5456,
//                         "product_id": 243842,
//                         "amount": 100,
//                         "uom": "(Gr)",
//                         "description": "{\"from\": \"Product\", \"type\": \"adding\", \"title\": \"Tambah stok produk baru\", \"amount\": \"100\"}",
//                         "status": 1,
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:45:28Z",
//                         "updated_at": "2024-11-21T10:45:28Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "product_photo": [
//                     {
//                         "id": 167690,
//                         "merchant_id": 5456,
//                         "product_id": 243842,
//                         "url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~products~1732160191d5a37b22-2eab-4069-babd-f154423b70c4.jpg",
//                         "created_by": null,
//                         "updated_by": null,
//                         "created_at": "2024-11-21T10:45:28Z",
//                         "updated_at": "2024-11-21T10:45:28Z",
//                         "deleted_at": null
//                     }
//                 ],
//                 "merchant": {
//                     "id": 5456,
//                     "name": "TOKO NAGA 2",
//                     "phone_office": "6281244001100",
//                     "corporate_id": 5456,
//                     "industry_type_id": null,
//                     "address": "Jl. Kh. Abdul Rochim No.1, RT.9/RW.1",
//                     "province_id": 11,
//                     "city_id": 156,
//                     "district_id": 1944,
//                     "postal_code": "12720",
//                     "longitude": "",
//                     "latitude": "",
//                     "email": "nagariaqa4@yopmail.com",
//                     "photo_url": null,
//                     "pic_id": 5456,
//                     "nib_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~1713411894db4e3c29-c69f-4e7a-b017-94b4fe99125a.jpg",
//                     "status": 1,
//                     "is_open": false,
//                     "slogan": "murah meriah makmur",
//                     "description": "sukses dan tentram dan aman aman saja",
//                     "registration_form_url": "",
//                     "created_by": "New Registration",
//                     "updated_by": "Service Provider",
//                     "reference_customer_id": "2028545",
//                     "created_at": "2024-04-18T10:44:55Z",
//                     "updated_at": "2025-01-09T00:51:01Z",
//                     "deleted_at": null,
//                     "whatsapp_number": "628",
//                     "has_custom_logistic": true,
//                     "can_test_drive": true,
//                     "district_code": null,
//                     "location_name": "",
//                     "can_credit": false,
//                     "official_store": false,
//                     "official_store_evds": false,
//                     "is_npwp_required": false,
//                     "official_store_tiket": false,
//                     "is_subsidy_ev": true,
//                     "store_umkm": false,
//                     "can_shipping_discount": true,
//                     "can_flash_sale_discount": true,
//                     "is_shipping_discount": false,
//                     "registration_via": "Mobile",
//                     "apicount": 0,
//                     "official_pln_mudik": false,
//                     "mitra_id": 0,
//                     "whitelist_suspend_scheduler": null,
//                     "subdistrict_id": 0,
//                     "last_transaction": null,
//                     "last_deposit": null,
//                     "last_deposit_val": null,
//                     "saldo": null,
//                     "is_voucher_ubah_daya": true,
//                     "background_url": "https://stamkp.beyondkwh.id/api/cdn/api/firebase/file/load/Marketplace~merchants~17200766147198fe1e-dab7-4a1e-8676-33b3c7b8cb52.jpg",
//                     "api_count": 0,
//                     "city": {
//                         "id": 0,
//                         "name": null
//                     },
//                     "expedition": {
//                         "id": 0,
//                         "list_expeditions": "",
//                         "merchant_id": 0,
//                         "created_at": null,
//                         "updated_at": null
//                     }
//                 },
//                 "ev_subsidy": null,
//                 "category": {
//                     "id": 501,
//                     "type": "product_category",
//                     "key": "prodcat_sepeda_listrik",
//                     "value_type": "string",
//                     "value": "Sepeda Listrik",
//                     "parent_id": 373,
//                     "reference_third_party_id": null,
//                     "reference_third_party_token": null,
//                     "photo_url": null,
//                     "created_by": "Service Provider",
//                     "updated_by": null,
//                     "created_at": "2022-01-27T13:59:56Z",
//                     "updated_at": "2022-01-27T13:59:56Z",
//                     "deleted_at": null,
//                     "max_variant": 0,
//                     "status": 1
//                 },
//                 "varian_product": null,
//                 "variants": null,
//                 "promo_value": 0,
//                 "promo_type": "",
//                 "reviews": null,
//                 "is_wishlist": null,
//                 "tiket": null,
//                 "promo_wording_title": null,
//                 "promo_wording_subtitle": null
//             }
//         ]
//     }
// }
